#!/bin/sh

# =========================
# 1. Set root password
# =========================
echo -e "Ir@q1984\nIr@q1984" | passwd root

# =========================
# 2. Set TTL value
# =========================
iptables -t mangle -I POSTROUTING -j TTL --ttl-set 65

# =========================
# 3. Configure WiFi
# =========================
uci set wireless.@wifi-iface[0].ssid='GT-King'
uci set wireless.@wifi-iface[0].disabled='0'
uci set wireless.@wifi-iface[0].encryption='psk2'

# Updated WiFi password
uci set wireless.@wifi-iface[0].key='12345678@'

uci commit wireless
wifi reload

# =========================
# End of script
# =========================
