#!/bin/sh

# =========================
# 1. Set root password
# =========================
echo -e "Ir@q1984\nIr@q1984" | passwd root

# =========================
# 2. Set TTL (IPv4 + IPv6)
# =========================
mkdir -p /etc/nftables.d

cat <<EOF > /etc/nftables.d/ttl65.nft
chain mangle_postrouting_ttl {
    type filter hook postrouting priority 300;
    ip ttl set 65
    ip6 hoplimit set 65
}
EOF

fw4 reload

# =========================
# 3. Configure WiFi
# =========================
uci set wireless.@wifi-iface[0].ssid='GT-King'
uci set wireless.@wifi-iface[0].disabled='0'
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.@wifi-iface[0].key='12345678@'

uci commit wireless
wifi reload

# =========================
# End of script
# =========================
